// Edgar.React/src/App.tsx
import './App.css';
import React, { useEffect, useState } from "react";
import Companies from "./Companies";
const rawDataUrl: string = `${process.env.REACT_APP_API_URL}/api/edgar/json`;
const requirementsUrl: string = `${process.env.REACT_APP_API_URL}/Fora Coding Challenge v1.1.pdf`;
const swaggerUrl: string = `${process.env.REACT_APP_API_URL}/swagger`;
let environmentName: string = '';
const copyrightYear: number = 2024;
const angularVersion: string = '17.2.1';

function App() {

    const [companies, setCompanies] = useState([]);
    const [author, setAuthor] = useState('');
    const [webSite, setWebSite] = useState('');
    const [pipeline, setPipeline] = useState('');
    const [repo, setRepo] = useState('');
    const [aspnetVersion, setAspnetVersion] = useState('');
    
    function filter(search:string) {
        
        let suffix = search === undefined || search.trim() === '' ? '' : `/${search}`;

        let url = `${process.env.REACT_APP_API_URL}/api/edgar/companies${suffix}`;

        fetch(url, { method: 'Get', mode: "cors" })
            .then(resp => resp.json())
            .then(data => setCompanies(data))
            .catch(error => console.error(error))
    }

      // A thrown-together way to force this component to update after companies are sorted.
    function useForceUpdate() {
        const [value, setValue] = useState(0); // integer state
        console.log(value);
        return () => setValue(value => value + 1); // update state to force render
        // A function that increments 👆🏻 the previous state like here 
        // is better than directly setting `setValue(value + 1)`
    }

    const forceUpdate = useForceUpdate();

    function onSort(companies: any) {
        setCompanies(companies);
        forceUpdate();
    }

    // Get All Companies
    useEffect(() => {
        fetch(`${process.env.REACT_APP_API_URL}/api/edgar/companies`, { method: 'Get', mode: "cors" })
          .then(resp => resp.json())
          .then(data => setCompanies(data))
          .catch(error => console.error(error))
      }, []);

    // Get Author
    useEffect(() => {
        fetch(`${process.env.REACT_APP_API_URL}/api/edgar/author`, { method: 'Get', mode: "cors" })
            .then(res => res.text())
            .then(result => setAuthor(result))
            .catch(error => console.error(error))
      }, []);
    
      // Get Website
      useEffect(() => {
        fetch(`${process.env.REACT_APP_API_URL}/api/edgar/website`, { method: 'Get', mode: "cors" })
          .then(resp => resp.text())
          .then(data => setWebSite(data))
          .catch(error => console.error(error))
      }, []);

      // Get Repo
      useEffect(() => {
        fetch(`${process.env.REACT_APP_API_URL}/api/edgar/repo`, { method: 'Get', mode: "cors" })
          .then(resp => resp.text())
          .then(data => setRepo(data))
          .catch(error => console.error(error))
      }, []);

      // Get Pipeline
      useEffect(() => {
        fetch(`${process.env.REACT_APP_API_URL}/api/edgar/pipeline`, { method: 'Get', mode: "cors" })
          .then(resp => resp.text())
          .then(data => setPipeline(data))
          .catch(error => console.error(error))
      }, []);

      // Get ASP.NET Version
      useEffect(() => {
        fetch(`${process.env.REACT_APP_API_URL}/api/edgar/aspnetVersion`, { method: 'Get', mode: "cors" })
          .then(resp => resp.text())
          .then(data => setAspnetVersion(data))
          .catch(error => console.error(error))
      }, []);

    switch (process.env.NODE_ENV?.toLowerCase()) {
        case "development":
        case "local": {
            environmentName = `- (${process.env.NODE_ENV})`;
            break;
        }
    }

  return (
    <>
            <div id="headingDiv" className="w3-row w3-theme-dark w3-padding-24">
                <div id="logoDiv" className="w3-col m3 w3-center">
                    <img src="https://www.sec.gov/files/sec-logo.png" alt="The Securities and Exchange Commission logo" title="The Securities and Exchange Commission logo" />
                    <p>This is NOT an official SEC app.</p>
                </div>
                <div id="brandDiv" className="w3-col m6 w3-center">
                    <h1 className="w3-xxxlarge">EDGAR Company Funding { environmentName }</h1>
                    <div className="w3-row">
                        <div className="w3-col s4"><a target="_blank" rel="noreferrer" title="Read the requirements" href={requirementsUrl}>Requirements</a></div>
                    <div className="w3-col s4"><a target="_blank" rel="noreferrer" title="See the raw data" href={rawDataUrl}>Data</a></div>
                <div className="w3-col s4"><a target="_blank" rel="noreferrer" title="Test the API" href={swaggerUrl}>API</a></div>
        </div >
  </div >
  <div id="authorDiv" className="w3-col m3">
                  <p>Created by <a target="_blank" rel="noreferrer" title="Get to know the author" href={webSite}>{author}</a></p>
    <p>Clone the <a target="_blank" rel="noreferrer" title="Clone the code" href={repo}>code repository</a></p >
        <p>View the <a target="_blank" rel="noreferrer" title="View the build/release pipeline" href={pipeline}>build/release pipeline</a></p >
            <p>A sample interview project for Fora Financial (www.forafinancial.com) and Soltech</p>
  </div >
</div >


<div className="w3-padding-24 w3-center">
  <h2>
    <div className="search-container w3-center">
                      <input id="searchInput" className="w3-border w3-round-xlarge w3-padding-14" type="text" autoComplete="off" onChange={(event) => filter(event.target.value)} placeholder="Company" />

      <div className="search-icon">
        <i className="fa fa-search"></i>
      </div>

    </div>
  </h2>
          </div>

<div className="w3-responsive">
  <Companies companies={companies} onSort={onSort}/>
</div >

        <footer className="w3-container w3-theme-dark w3-padding-16 w3-center">
            <h3>Created with ASP.NET Core { aspnetVersion }, Node 18.19.1, and Angular { angularVersion }</h3>
            <p className="w3-tiny">&copy; { copyrightYear }. All rights reserved.</p>
        </footer>
    </>
  )
}

export default App

// Soltech.Samples.Fora.EdgarClient/src/app/app.component.ts
import { HttpClient } from '@angular/common/http';
import { Component, OnInit } from '@angular/core';
import { environment } from '../environments/environment';
import { CurrencyPipe } from '@angular/common';

interface Company {
  id: number;
  name: string;
  standardFundableAmount: number;
  specialFundableAmount: number;
}


@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrl: './app.component.css'
})
export class AppComponent implements OnInit {

  public companies: Company[] = [];
  public author: string = '';
  public website: string = '';
  public repo: string = '';
  public rawDataUrl: string = `${environment.apiUrl}/api/edgar/json`;
  public requirementsUrl: string = `${environment.apiUrl}/Fora Coding Challenge v1.1.pdf`;
  public swaggerUrl: string = `${environment.apiUrl}/swagger`;
  search: string = '';

  constructor(private http: HttpClient) {}

  ngOnInit() {
    this.getCompanies();
    this.getAuthor();
    this.getWebsite();
    this.getRepository();
  }

  getCompanies() {
    this.http.get<Company[]>(`${environment.apiUrl}/api/edgar/companies`).subscribe(
      (result) => {
        this.companies = result;
      },
      (error) => {
        console.error(error);
      }
    )
  }

  filter() {
    if (this.search == undefined || this.search.trim() == '') {
      this.getCompanies();
      return;
    }

    this.http.get<Company[]>(`${environment.apiUrl}/api/edgar/companies/${this.search}`).subscribe(
      (result) => {
        this.companies = result;
      },
      (error) => {
        console.error(error);
      }
    )
  }

  getAuthor() {
    this.http.get(`${environment.apiUrl}/api/edgar/author`, { responseType: 'text' }).subscribe(
      (result) => {
        this.author = `${result}`;
      },
      (error) => {
        console.error(error);
      }
    )
  }

  getWebsite() {
    this.http.get(`${environment.apiUrl}/api/edgar/website`, { responseType: 'text' }).subscribe(
      (result) => {
        this.website = `${result}`;
      },
      (error) => {
        console.error(error);
      }
    )
  }

  getRepository() {
    this.http.get(`${environment.apiUrl}/api/edgar/repo`, { responseType: 'text' }).subscribe(
      (result) => {
        this.repo = `${result}`;
      },
      (error) => {
        console.error(error);
      }
    )
  }

  title = 'EDGAR Company Funding';
}

<div id="headingDiv" class="w3-row w3-theme-dark w3-padding-24">
  <div id="logoDiv" class="w3-col m3 w3-center">
    <img src="https://www.sec.gov/files/sec-logo.png" alt="The Securities and Exchange Commission logo" title="The Securities and Exchange Commission logo" />
    <p>This is NOT an official SEC app.</p>
  </div>
  <div id="brandDiv" class="w3-col m6 w3-center">
    <h1 class="w3-xxxlarge">EDGAR Company Funding {{environmentName}}</h1>
    <div class="w3-row">
      <div class="w3-col s4"><a target="_blank" title="Read the requirements" [href]="requirementsUrl">Requirements</a></div>
      <div class="w3-col s4"><a target="_blank" title="See the raw data" [href]="rawDataUrl">Data</a></div>
      <div class="w3-col s4"><a target="_blank" title="Test the API" [href]="swaggerUrl">API</a></div>
    </div>
  </div>
  <div id="authorDiv" class="w3-col m3">
    <p>Created by <a target="_blank" title="Get to know the author" [href]="website" [textContent]="author"></a></p>
    <p>Clone the <a target="_blank" title="Clone the code" [href]="repo">code repository</a></p>
    <p>View the <a target="_blank" title="View the build/release pipeline" [href]="pipeline">build/release pipeline</a></p>
    <p>A sample interview project for Fora Financial (www.forafinancial.com) and Soltech</p>
  </div>
</div>


<div class="w3-padding-24">
  <h2>
    <div class="search-container">
      <input id="searchInput" class="w3-border w3-round-xlarge w3-padding-14" type="text" (input)='filter()' [(ngModel)]="search" placeholder="Company" />

      <!-- Search icon -->
      <div class="search-icon">
        <i class="fa fa-search"></i>
      </div>

    </div>
  </h2>
</div>

<p *ngIf="!companies"><em>Loading... Please refresh after a few seconds. See <a href="https://aka.ms/jspsintegrationangular">https://aka.ms/jspsintegrationangular</a> for more details.</em></p>

<div class="w3-responsive">
  <table *ngIf="companies" class="w3-table-striped">
    <thead>
      <tr class="w3-theme-dark">
        <th><span (click)="sort('id')">CIK</span></th>
        <th><span (click)="sort('name')">Name</span></th>
        <th><span (click)="sort('standardFundableAmount')">Standard Fundable Amount</span></th>
        <th><span (click)="sort('specialFundableAmount')">Special Fundable Amount</span></th>
      </tr>
    </thead>
    <tbody>
      <tr *ngFor="let company of companies">
        <td>{{ company.id }}</td>
        <td>{{ company.name }}</td>
        <td>{{ company.standardFundableAmount | currency }}</td>
        <td>{{ company.specialFundableAmount | currency }}</td>
      </tr>
    </tbody>
  </table>
</div>

<footer class="w3-container w3-theme-dark w3-padding-16 w3-center">
  <h3>Created with ASP.NET Core {{aspnetVersion}}, Node 18.19.1, and Angular {{angularVersion}}</h3>
  <p className="w3-tiny">&copy; {{copyrightYear}}. All rights reserved.</p>
</footer>
